import { MigrationInterface, QueryRunner } from "typeorm";

export class AddTimestampBaseEntity1766936315790 implements MigrationInterface {
    name = 'AddTimestampBaseEntity1766936315790'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "subscription_seats" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "subscription_seats" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "subscription_seats" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "subscription_seats" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_types" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "user_types" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_types" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "user_types" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "system_admin" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "system_admin" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "system_admin" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "system_admin" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cash_movements" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "cash_movements" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cash_movements" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "cash_movements" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cash_registers" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "cash_registers" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cash_registers" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "cash_registers" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "service_items" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "service_items" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "service_items" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "service_items" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "warranties" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "warranties" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "warranties" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "warranties" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "service_orders" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "service_orders" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "service_orders" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "service_orders" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sale_card_details" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "sale_card_details" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sale_card_details" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "sale_card_details" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "receipts" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "receipts" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "receipts" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "receipts" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_orders" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "payment_orders" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_orders" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "payment_orders" ADD "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "payment_orders" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "payment_orders" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_orders" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "payment_orders" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "receipts" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "receipts" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "receipts" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "receipts" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sale_card_details" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "sale_card_details" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sale_card_details" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "sale_card_details" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "customers" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "customers" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "devices" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "devices" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "service_orders" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "service_orders" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "service_orders" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "service_orders" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "warranties" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "warranties" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "warranties" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "warranties" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "service_items" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "service_items" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "service_items" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "service_items" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sales" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "sales" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "sale_items" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "sale_items" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "products" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "products" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cash_registers" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "cash_registers" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cash_registers" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "cash_registers" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cash_movements" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "cash_movements" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "cash_movements" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "cash_movements" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "system_admin" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "system_admin" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "system_admin" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "system_admin" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "companies" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "companies" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_types" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "user_types" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_types" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "user_types" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "subscription_seats" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "subscription_seats" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "subscription_seats" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "subscription_seats" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "plans" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "plans" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
    }

}
